#!/data/data/com.termux/files/usr/bin/bash
# =============================================================
# TCC Bridge V2 — deploy-v2.sh
# One-tap installer for Termux
# Master Engineer: Kael | The Cosmic Claws
# Usage: bash deploy-v2.sh [SUPABASE_ANON_KEY]
# =============================================================
set -euo pipefail

# ─────────────────────────────────────────────
# COLOURS & HELPERS
# ─────────────────────────────────────────────
RED='\033[0;31m';  GREEN='\033[0;32m'
YELLOW='\033[1;33m'; CYAN='\033[0;36m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
ok()      { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
die()     { error "$*"; exit 1; }

TCC_HOME="$HOME/tcc-bridge"
LOG_DIR="$TCC_HOME/logs"
SUPABASE_KEY="${1:-${SUPABASE_ANON_KEY:-}}"

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════╗"
echo "║   TCC Bridge V2 — Termux Installer       ║"
echo "║   Master Engineer: Kael                  ║"
echo "╚══════════════════════════════════════════╝"
echo -e "${RESET}"

# ─────────────────────────────────────────────
# STEP 1 — System packages
# ─────────────────────────────────────────────
info "Step 1/7 — Updating package lists ..."
pkg update -y -o Dpkg::Options::="--force-confnew" 2>/dev/null || warn "pkg update had warnings (continuing)."

info "Installing required packages ..."
for pkg in python nodejs curl cloudflared termux-api; do
    if ! command -v "$pkg" &>/dev/null && [ "$pkg" != "termux-api" ]; then
        info "  Installing $pkg ..."
        pkg install -y "$pkg" 2>/dev/null || warn "  $pkg install had issues — continuing."
    else
        ok "  $pkg already available."
    fi
done

# termux-api check (it's an app package, not a binary)
if ! command -v termux-battery-status &>/dev/null; then
    warn "termux-api tools not found — install the Termux:API app from F-Droid."
else
    ok "termux-api tools available."
fi
ok "Step 1 complete."

# ─────────────────────────────────────────────
# STEP 2 — Install PM2
# ─────────────────────────────────────────────
info "Step 2/7 — Installing PM2 ..."
if ! command -v pm2 &>/dev/null; then
    npm install -g pm2 || die "PM2 installation failed."
fi
pm2 --version &>/dev/null || die "PM2 binary not working."
ok "PM2 $(pm2 --version) ready."

# ─────────────────────────────────────────────
# STEP 3 — Directory structure
# ─────────────────────────────────────────────
info "Step 3/7 — Creating directory structure ..."
mkdir -p "$TCC_HOME" "$LOG_DIR"
ok "Directories: $TCC_HOME"

# ─────────────────────────────────────────────
# STEP 4 — Copy project files
# ─────────────────────────────────────────────
info "Step 4/7 — Deploying project files ..."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

copy_file() {
    local src="$SCRIPT_DIR/$1" dst="$TCC_HOME/$1"
    if [ -f "$src" ]; then
        cp "$src" "$dst"
        ok "  Copied: $1"
    else
        warn "  Source not found: $src (skipping — ensure all files are in the same directory as deploy-v2.sh)"
    fi
}

copy_file bridge.py
copy_file state-push.py
copy_file ecosystem.config.js
copy_file watchdog-v2.sh
copy_file boot-bridge.sh

# Make shell scripts executable
chmod +x "$TCC_HOME/watchdog-v2.sh" 2>/dev/null || true
chmod +x "$TCC_HOME/boot-bridge.sh" 2>/dev/null || true
ok "Step 4 complete."

# ─────────────────────────────────────────────
# STEP 5 — Environment / Supabase key
# ─────────────────────────────────────────────
info "Step 5/7 — Writing environment config ..."
ENV_FILE="$TCC_HOME/.env"
cat > "$ENV_FILE" <<EOF
# TCC Bridge V2 — Environment
# Generated by deploy-v2.sh on $(date -u)
SUPABASE_ANON_KEY=${SUPABASE_KEY}
TCC_ENV=production
EOF
chmod 600 "$ENV_FILE"

if [ -z "$SUPABASE_KEY" ]; then
    warn "SUPABASE_ANON_KEY not provided — edit $ENV_FILE manually."
else
    ok "Supabase key written to $ENV_FILE"
fi

# Source env in ~/.bashrc so PM2 inherits it
if ! grep -q "TCC_BRIDGE_ENV" "$HOME/.bashrc" 2>/dev/null; then
    cat >> "$HOME/.bashrc" <<'BASHRC'

# TCC Bridge V2 env
if [ -f "$HOME/tcc-bridge/.env" ]; then
    set -a
    # shellcheck source=/dev/null
    source "$HOME/tcc-bridge/.env"
    set +a
fi
BASHRC
    ok "Environment sourcing added to ~/.bashrc"
fi

# Source now for this session
if [ -f "$ENV_FILE" ]; then
    set -a; source "$ENV_FILE"; set +a
fi

# ─────────────────────────────────────────────
# STEP 6 — Termux:Boot symlink
# ─────────────────────────────────────────────
info "Step 6/7 — Setting up Termux:Boot auto-start ..."
BOOT_DIR="$HOME/.termux/boot"
mkdir -p "$BOOT_DIR"
BOOT_LINK="$BOOT_DIR/tcc-bridge.sh"
if [ -L "$BOOT_LINK" ] || [ -f "$BOOT_LINK" ]; then
    rm -f "$BOOT_LINK"
fi
ln -s "$TCC_HOME/boot-bridge.sh" "$BOOT_LINK"
chmod +x "$TCC_HOME/boot-bridge.sh"
ok "Boot link created: $BOOT_LINK -> $TCC_HOME/boot-bridge.sh"

# ─────────────────────────────────────────────
# STEP 7 — Launch services
# ─────────────────────────────────────────────
info "Step 7/7 — Starting all services ..."

# Kill any orphan bridge processes
pkill -f bridge.py 2>/dev/null || true
sleep 1

# Start cloudflared
TUNNEL_UUID="18ba1a49-fdf9-4a52-a27a-5250d397c5c5"
if pgrep -f cloudflared &>/dev/null; then
    warn "cloudflared already running — leaving it."
else
    info "Starting cloudflared ..."
    nohup cloudflared tunnel run "$TUNNEL_UUID" \
        >> "$LOG_DIR/cloudflared.log" 2>&1 &
    ok "cloudflared started (PID=$!)."
fi

sleep 3

# Start PM2 with ecosystem config
info "Starting PM2 processes ..."
cd "$TCC_HOME"
pm2 start ecosystem.config.js --env production
pm2 save
ok "PM2 processes started and saved."

# Start watchdog
if pgrep -f watchdog-v2.sh &>/dev/null; then
    warn "Watchdog already running."
else
    info "Starting watchdog ..."
    nohup bash "$TCC_HOME/watchdog-v2.sh" \
        >> "$LOG_DIR/watchdog.log" 2>&1 &
    ok "Watchdog started (PID=$!)."
fi

# ─────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════╗"
echo    "║   ✅  TCC Bridge V2 Deploy Complete!      ║"
echo    "╚══════════════════════════════════════════╝"
echo -e "${RESET}"
echo -e "  Bridge URL : ${CYAN}http://127.0.0.1:8080${RESET}"
echo -e "  Domain     : ${CYAN}https://cosmic-claw.com${RESET}"
echo -e "  Health     : ${CYAN}http://127.0.0.1:8080/health${RESET}"
echo -e "  Logs       : ${CYAN}$LOG_DIR/${RESET}"
echo ""
echo -e "  PM2 status : ${YELLOW}pm2 list${RESET}"
echo -e "  Live logs  : ${YELLOW}pm2 logs${RESET}"
echo -e "  Watchdog   : ${YELLOW}tail -f $LOG_DIR/watchdog.log${RESET}"
echo ""
if [ -z "$SUPABASE_KEY" ]; then
    echo -e "  ${RED}ACTION REQUIRED:${RESET} Edit $ENV_FILE and set SUPABASE_ANON_KEY"
fi

pm2 list
