// TCC Bridge V2 — PM2 Ecosystem Config
// Kael the God Builder Edition

module.exports = {
  apps: [
    {
      name: "tcc-bridge",
      script: "python3",
      args: "bridge_v2.py",
      cwd: "/data/data/com.termux/files/home/tcc-bridge",
      interpreter: "none",
      autorestart: true,
      watch: false,
      max_memory_restart: "150M",
      restart_delay: 5000,
      max_restarts: 20,
      min_uptime: "10s",
      exp_backoff_restart_delay: 2000,
      kill_timeout: 5000,
      listen_timeout: 10000,
      error_file: "/data/data/com.termux/files/home/logs/bridge-error.log",
      out_file:   "/data/data/com.termux/files/home/logs/bridge-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      env: {
        PORT:        "8765",
        SUPABASE_URL: "https://vbqbbziqleymxcyesmky.supabase.co",
        SUPABASE_KEY: "sb_secret_lIbl-DBgdnrt_fejgJjKqg_qR62SVEm",
        NTFY_TOPIC:   "zenith-escape",
        NTFY_HIVE:    "tcc-zenith-hive",
        PUBLIC_URL:   "https://zenith.cosmic-claw.com",
        PYTHONUNBUFFERED: "1",
      },
    },

    {
      name: "tcc-server",
      script: "python3",
      args: "server.py",
      cwd: "/data/data/com.termux/files/home/tcc-bridge",
      interpreter: "none",
      autorestart: true,
      watch: false,
      max_memory_restart: "100M",
      restart_delay: 5000,
      max_restarts: 20,
      min_uptime: "10s",
      exp_backoff_restart_delay: 2000,
      kill_timeout: 5000,
      error_file: "/data/data/com.termux/files/home/logs/server-error.log",
      out_file:   "/data/data/com.termux/files/home/logs/server-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      env: {
        BRIDGE_AUTH: "amos-bridge-2026",
        SUPABASE_URL: "https://vbqbbziqleymxcyesmky.supabase.co",
        SUPABASE_KEY: "sb_secret_lIbl-DBgdnrt_fejgJjKqg_qR62SVEm",
        PYTHONUNBUFFERED: "1",
      },
    },

    {
      name: "cloudflared",
      script: "cloudflared",
      args: "tunnel --config /data/data/com.termux/files/home/.cloudflared/config.yml run 18ba1a49-fdf9-4a52-a27a-5250d397c5c5",
      interpreter: "none",
      autorestart: true,
      watch: false,
      max_memory_restart: "80M",
      restart_delay: 10000,
      max_restarts: 50,
      min_uptime: "5s",
      exp_backoff_restart_delay: 5000,
      kill_timeout: 8000,
      error_file: "/data/data/com.termux/files/home/logs/cloudflared-error.log",
      out_file:   "/data/data/com.termux/files/home/logs/cloudflared-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
